{"identifier":{"url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/error","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"abstract":[{"type":"text","text":"Error involved in the error."}],"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"metadata":{"roleHeading":"Instance Property","title":"error","symbolKind":"property","role":"symbol","modules":[{"name":"SnowplowTracker"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":"?"}],"externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)error"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"error","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5ErrorP","text":"Error","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["macOS"]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/snowplowtracker\/trackererror\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://SnowplowTracker/documentation/SnowplowTracker":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/snowplowtracker","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","abstract":[],"title":"SnowplowTracker"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/error":{"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/error","role":"symbol","abstract":[{"type":"text","text":"Error involved in the error."}],"type":"topic","title":"error","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"error","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":"?","kind":"text"}],"url":"\/documentation\/snowplowtracker\/trackererror\/error","kind":"symbol"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"url":"\/documentation\/snowplowtracker\/trackererror","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TrackerError","kind":"identifier"}],"navigatorTitle":[{"text":"TrackerError","kind":"identifier"}],"abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","kind":"symbol","type":"topic","title":"TrackerError","role":"symbol"}}}