{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/snowplowtracker\/trackererror\/error"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/error","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Error involved in the error."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"title":"error","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)error","modules":[{"name":"SnowplowTracker"}]},"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"role":"symbol","title":"TrackerError","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"TrackerError"}],"abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"TrackerError"}],"url":"\/documentation\/snowplowtracker\/trackererror"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/error":{"role":"symbol","title":"error","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Error involved in the error."}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/error","kind":"symbol","type":"topic","url":"\/documentation\/snowplowtracker\/trackererror\/error"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"role":"collection","title":"SnowplowTracker","abstract":[],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","kind":"symbol","type":"topic","url":"\/documentation\/snowplowtracker"}}}