{"abstract":[{"type":"text","text":"Message of the error."}],"metadata":{"roleHeading":"Instance Property","role":"symbol","modules":[{"name":"SnowplowTracker"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"symbolKind":"property","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)message","title":"message"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/trackererror\/message"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/message":{"kind":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message","abstract":[{"type":"text","text":"Message of the error."}],"title":"message","url":"\/documentation\/snowplowtracker\/trackererror\/message","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"kind":"symbol","navigatorTitle":[{"text":"TrackerError","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"url":"\/documentation\/snowplowtracker\/trackererror","title":"TrackerError","role":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TrackerError","kind":"identifier"}]},"doc://SnowplowTracker/documentation/SnowplowTracker":{"title":"SnowplowTracker","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","role":"collection","kind":"symbol","url":"\/documentation\/snowplowtracker","type":"topic","abstract":[]}}}