{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["macOS"],"tokens":[{"text":"@objc","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"message"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"text":"Message of the error.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"modules":[{"name":"SnowplowTracker"}],"title":"message","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)message","role":"symbol","roleHeading":"Instance Property","symbolKind":"property"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message"},"variants":[{"paths":["\/documentation\/snowplowtracker\/trackererror\/message"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/message":{"abstract":[{"type":"text","text":"Message of the error."}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message","kind":"symbol","title":"message","url":"\/documentation\/snowplowtracker\/trackererror\/message","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"message"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"title":"SnowplowTracker","role":"collection","url":"\/documentation\/snowplowtracker","type":"topic","kind":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","abstract":[]},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","kind":"symbol","title":"TrackerError","navigatorTitle":[{"kind":"identifier","text":"TrackerError"}],"url":"\/documentation\/snowplowtracker\/trackererror","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TrackerError","kind":"identifier"}],"role":"symbol"}}}