{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/trackererror\/message"]}],"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message"},"abstract":[{"type":"text","text":"Message of the error."}],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"sections":[],"metadata":{"roleHeading":"Instance Property","modules":[{"name":"SnowplowTracker"}],"role":"symbol","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)message","symbolKind":"property","title":"message","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/message":{"kind":"symbol","role":"symbol","type":"topic","title":"message","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message","url":"\/documentation\/snowplowtracker\/trackererror\/message","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"Message of the error."}]},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"url":"\/documentation\/snowplowtracker\/trackererror","abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"navigatorTitle":[{"text":"TrackerError","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TrackerError","kind":"identifier"}],"type":"topic","title":"TrackerError"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"abstract":[],"type":"topic","kind":"symbol","title":"SnowplowTracker","role":"collection","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","url":"\/documentation\/snowplowtracker"}}}