{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"message"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/trackererror\/message"]}],"abstract":[{"type":"text","text":"Message of the error."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message"},"metadata":{"title":"message","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)message","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"modules":[{"name":"SnowplowTracker"}],"symbolKind":"property"},"references":{"doc://SnowplowTracker/documentation/SnowplowTracker":{"kind":"symbol","type":"topic","role":"collection","url":"\/documentation\/snowplowtracker","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","abstract":[],"title":"SnowplowTracker"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/message":{"kind":"symbol","title":"message","url":"\/documentation\/snowplowtracker\/trackererror\/message","type":"topic","abstract":[{"text":"Message of the error.","type":"text"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"message","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/message"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"url":"\/documentation\/snowplowtracker\/trackererror","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"TrackerError","kind":"identifier"}],"navigatorTitle":[{"text":"TrackerError","kind":"identifier"}],"abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","kind":"symbol","type":"topic","title":"TrackerError","role":"symbol"}}}