{"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"abstract":[{"type":"text","text":"Class name or source where the error appeared."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Instance Property","title":"source","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)source","modules":[{"name":"SnowplowTracker"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["macOS"]}]}],"variants":[{"paths":["\/documentation\/snowplowtracker\/trackererror\/source"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/source"},"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/source":{"url":"\/documentation\/snowplowtracker\/trackererror\/source","title":"source","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"abstract":[{"text":"Class name or source where the error appeared.","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/source"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"title":"SnowplowTracker","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","role":"collection","kind":"symbol","url":"\/documentation\/snowplowtracker","type":"topic","abstract":[]},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"kind":"symbol","navigatorTitle":[{"text":"TrackerError","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Tracker error event used in diagnostic autotracking."}],"url":"\/documentation\/snowplowtracker\/trackererror","title":"TrackerError","role":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TrackerError","kind":"identifier"}]}}}