{"kind":"symbol","abstract":[{"text":"Class name or source where the error appeared.","type":"text"}],"sections":[],"metadata":{"title":"source","role":"symbol","externalID":"c:@M@SnowplowTracker@objc(cs)SPTrackerError(py)source","modules":[{"name":"SnowplowTracker"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"source","kind":"identifier"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property"},"variants":[{"paths":["\/documentation\/snowplowtracker\/trackererror\/source"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/source"},"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"attribute","text":"@objc"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"source"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"platforms":["macOS"]}]}],"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError/source":{"abstract":[{"type":"text","text":"Class name or source where the error appeared."}],"url":"\/documentation\/snowplowtracker\/trackererror\/source","kind":"symbol","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError\/source","title":"source","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"source","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"type":"topic"},"doc://SnowplowTracker/documentation/SnowplowTracker":{"type":"topic","url":"\/documentation\/snowplowtracker","title":"SnowplowTracker","abstract":[],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","role":"collection","kind":"symbol"},"doc://SnowplowTracker/documentation/SnowplowTracker/TrackerError":{"kind":"symbol","url":"\/documentation\/snowplowtracker\/trackererror","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/TrackerError","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"TrackerError","kind":"identifier"}],"title":"TrackerError","type":"topic","abstract":[{"text":"Tracker error event used in diagnostic autotracking.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"TrackerError","kind":"identifier"}]}}}