{"sections":[],"metadata":{"roleHeading":"Instance Property","externalID":"c:@M@SnowplowTracker@objc(cs)SPSNOWError(py)stackTrace","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"stackTrace"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"stackTrace","symbolKind":"property","modules":[{"name":"SnowplowTracker"}],"role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/SNOWError\/stackTrace"},"hierarchy":{"paths":[["doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/SNOWError"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["macOS"],"languages":["swift"],"tokens":[{"text":"@objc","kind":"attribute"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"stackTrace"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/snowplowtracker\/snowerror\/stacktrace"]}],"abstract":[{"type":"text","text":"Stacktrace for the error"}],"references":{"doc://SnowplowTracker/documentation/SnowplowTracker/SNOWError/stackTrace":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"stackTrace","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?"}],"kind":"symbol","title":"stackTrace","type":"topic","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/SNOWError\/stackTrace","url":"\/documentation\/snowplowtracker\/snowerror\/stacktrace","abstract":[{"type":"text","text":"Stacktrace for the error"}],"role":"symbol"},"doc://SnowplowTracker/documentation/SnowplowTracker/SNOWError":{"navigatorTitle":[{"text":"SNOWError","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SNOWError","kind":"identifier"}],"identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker\/SNOWError","url":"\/documentation\/snowplowtracker\/snowerror","title":"SNOWError","kind":"symbol","abstract":[{"type":"text","text":"Error event tracked by exception autotracking."}]},"doc://SnowplowTracker/documentation/SnowplowTracker":{"title":"SnowplowTracker","role":"collection","kind":"symbol","type":"topic","identifier":"doc:\/\/SnowplowTracker\/documentation\/SnowplowTracker","url":"\/documentation\/snowplowtracker","abstract":[]}}}